require('plugins.bufferline')
require('plugins.flash')
require('plugins.lsp')
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.colorscheme')
require('plugins.lualine')
require('plugins.telescope')
