require("startup").setup({
  header = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Header",
        margin = 5,
        content = {
            " ███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗",
            " ████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║",
            " ██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║",
            " ██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║",
            " ██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║",
            " ╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝",
        },
        highlight = "Statement",
        default_color = "",
        oldfiles_amount = 0,
    },
   myHeader = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Header",
        margin = 5,
        content = {
            "⢠⣤⣤⡀  ⣤⣤⡄ ⣤⣤          ⢠⣤⡄  ⢀⣤⣤⡤          ⣤⣤             ",
            " ⠹⣿⣧⡀⣴⣿⠏  ⣙⣛ ⢀⣀⡀⢀⣀⣀⡀  ⢸⣿⡇ ⣠⣾⡿⠋  ⣀⣀   ⣀⣀  ⣿⣿       ⢀⣀⣀⣀  ",
            "  ⠈⢿⣿⣿⠉   ⣿⣿ ⢸⣿⡷⠛⠛⢻⣿⡆ ⢸⣿⣷⣾⣿⣏    ⣿⣿   ⣿⣿  ⣿⣿      ⣶⣿⠛⠛⢿⣷⡆",
            "  ⣤⣿⠿⣿⣦⡀  ⣿⣿ ⢸⣿⡇  ⢸⣿⡇ ⢸⣿⡟⠋⢿⣿⣆⡀  ⣿⣿   ⣿⣿  ⣿⣿      ⣿⡷⠶⠶⠾⠿⠷",
            "⢠⣼⣿⠏ ⠘⣿⣷⣀ ⣿⣿ ⢸⣿⡇  ⢸⣿⡇ ⢸⣿⡇  ⠙⣿⣷⣄ ⠹⣿⣦⣤⡶⣿⣿  ⣿⣿⣶⣶⣶⣶⣶ ⠻⣿⣤⣤⣶⡶⠆",
            "⠉⠉⠉   ⠉⠉⠉ ⠉⠉ ⠈⠉⠁  ⠈⠉⠁ ⠈⠉⠁   ⠈⠉⠉  ⠈⠉⠉ ⠉⠉  ⠉⠉⠉⠉⠉⠉⠉  ⠈⠉⠉⠉  ",
        },
        highlight = "",
        default_color = "",
        oldfiles_amount = 0,
    },
   footer = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Footer",
        margin = 5,
        content = { "Have a Nice Day!" },
        highlight = "String",
        oldfiles_amount = 0,
   },
    

    options = {
        mapping_keys = true,
        cursor_column = 0.5,
        empty_lines_between_mappings = true,
        disable_statuslines = true,
        paddings = { 15, 5},
    },
    mappings = {
        execute_command = "<CR>",
        open_file = "o",
        open_file_split = "<c-o>",
        open_section = "<TAB>",
        open_help = "?",
    },
    colors = {
        background = "#1f2227",
        folded_section = "#56b6c2",
    },
    parts = { "header", "footer"}, 
})
-- default dashboard: https://github.com/startup-nvim/startup.nvim/blob/master/lua/startup/themes/dashboard.lua
